In [1]:
from sklearn.cluster import KMeans

import numpy as np

X = np.array([
              [12.93,77.4472],
              [12.32,77.4472], 
              [12.51,77.4472],
              [12.62,77.4472],
              [12.73,77.4472], 
              [12.84,76.4158],
              [12.91,76.4158],
              [12.41,76.4158], 
              [12.92,76.4158],
              [12.55,76.4158], 
             ])

kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

kmeans.labels_
 

      

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int32)

In [2]:
kmeans.cluster_centers_
           


array([[12.726 , 76.4158],
       [12.622 , 77.4472]])

In [3]:
kmeans.predict([[12.88, 76.88]])

array([0], dtype=int32)